title: "Tavus AI Chat"
description: "A simple site to integrate Tavus AI Chat."
baseurl: "/CVI" # Match your GitHub repository name
url: "https://flippodlabs.github.io" # Your GitHub Pages URL
theme: minima
plugins:
  - jekyll-feed
